#!/bin/bash
sudo systemctl restart isc-dhcp-server
sudo systemctl status  isc-dhcp-server 1>./null 2>./null
if [ $? -eq 0 ]
then
   cp ./tools/running.txt ./laravel/public/php_save/dhcp_state.txt 
else

    cp ./tools/not-running.txt ./laravel/public/php_save/dhcp_state.txt
fi

sudo systemctl restart -q nginx 
if [ $? -eq 0 ]
then
    cp ./tools/running.txt ./laravel/public/php_save/nginx_state.txt
else

    cp ./tools/not-running.txt ./laravel/public/php_save/nginx_state.txt
fi

sudo systemctl restart -q vsftpd
if [ $? -eq 0 ]
then
    cp ./tools/running.txt ./laravel/public/php_save/ftp_state.txt
else
    cp ./tools/not-running.txt ./laravel/public/php_save/ftp_state.txt
fi

sudo php ./laravel/artisan serve
